### PR TITLE
Add "Model" in each className

### PR DESCRIPTION
**Pull request by wvqusrtg**
Hi,Ahmed-Ali;For your project :JSONExport ,Update by myself(Add "Model" in each [className)](https://github.com/wvqusrtg/JSONExport)

### CODE REVIEW

**Comment by wvqusrtg** [comment]
Hi,Ahmed-Ali;For your project :JSONExport ,Update by myself(Add "Model" in each className)

**Comment by wvqusrtg** [comment]
Hi,Ahmed-Ali;For your project :JSONExport ,Update by myself(Add "Model" in each className)
-NickName:nixs
-Email:nixs2016@icloud.com

**Comment by Ahmed-Ali** [comment]
Hi @wvqusrtg thanks a lot for your contribution.
What do you think about providing a text field for class suffix (like the one already there for class prefix) so people can choose either "Model" as you do, or whatever suits their team convention?

**Comment by wvqusrtg** [comment]
Well, 1, general "Model" suffix that people get more at a glance know this is a Model class, the same principles apply to other languages.2, 1, of course, is not absolute, in view of the different teams can, of course, add some of your team custom prefix or suffix.3, "JSONExport" starting can best give custom prefix or suffix visual configuration Settings;

**Pull request closed without merging**
