### PR TITLE
Load JSON data from web

### PR DESCRIPTION
**Pull request by rogys88**
Fixed issue (#148) - App getting crash while passing proper json.

Task/Issue URL: https://github.com/Ahmed-Ali/JSONExport/issues/148

### CODE REVIEW

**Comment by rogys88** [comment]
### Support for loading JSON data from web


Screen Shot 2022-10-18 at 1 47 21 PM

**Comment by Ahmed-Ali** [comment]
Hi @rogys88, first off thank you so much for the PR! second off, I am really sorry it took so long to get to it. I promise I will do my best to be much more attentive for future PRs.

Lastly, if you can kindly revise the PR to resolve the conflicts, and update it to request to merge to develop instead of the master branch, that would be really appreciated!

**Comment by rogys88** [comment]
> Hi @rogys88, first off thank you so much for the PR! second off, I am really sorry it took so long to get to it. I promise I will do my best to be much more attentive for future PRs.
> 
> Lastly, if you can kindly revise the PR to resolve the conflicts, and update it to request to merge to develop instead of the master branch, that would be really appreciated!

I just did it 😉

**Comment by Ahmed-Ali** [comment]
Thanks @rogys88! I believe you did that in PR #153 which is now merged. Hence I will close this one.

**Pull request closed without merging**
